### ISSUE TITLE
HSL colors instead of HEX

### ISSUE THREAD

**Issue by hans2103** [EightShapes/contrast-grid#16]
I would like to use HSL colors instead of HEX colors. 
At this moment this is not possible. Can this option be added too?

**Comment by frankstallone** [comment]
I second this. Came to Github to see if it accepted HSL before even trying.

**Comment by mherchel** [comment]
+1 on this

**Comment by SCPCOEXR** [comment]
Will this be an option sometime? Thank you.

**Comment by mherchel** [comment]
@SCPCOEXR FYI, I built a similar tool that has this functionality over at https://contrastgrid.com/

**Comment by SCPCOEXR** [comment]
> @SCPCOEXR FYI, I built a similar tool that has this functionality over at https://contrastgrid.com/

I don't think I've ever had a response so quickly handled with an answer on Github for all the years I've been on it. Thank you for this. I appreciate it!

**Comment by hans2103** [comment]
:wastebasket: house cleaning my issues. Closing this one because it will never be implemented
